name: noah_ark
description: Noah's Ark Application
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+5
  firebase_database: ^3.0.2
  firebase_auth: ^0.11.1+6
  font_awesome_flutter: ^8.4.0
  carousel_pro: ^0.0.1
  tiny_widgets:
    git: https://github.com/TinyProgrammers/tiny_widgets.git

flutter:
  uses-material-design: true
  assets:
    - assets/ads/
    - assets/images/
    - assets/icons/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
    - family: Sitka
      fonts:
        - asset: assets/fonts/Sitka.ttc
    - family: Hacen
      fonts:
        - asset: assets/fonts/Hacen_Saudi_Arabia.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial Narrow.ttf
